version: 0.2
phases:
  install:
    commands:
      - python --version
      - which pip
      - pip --version
      - pwd
      - ls
      - aws s3 ls
      - pip install -r requirements.txt
      - pip install -e .
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - env
  build:
    commands:
      - echo Entering build phase...
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
