version: 0.2
phases:
  install:
    commands:
      - python --version
      - which pip
      - pip --version
      - pwd
      - ls
      - aws s3 ls
      - pip install -r requirements.txt
      - pip install -e .
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - pytest ./tests
      - pylint ./sercices
      - env
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo Entering build phase...
  post_build:
    commands:
      -
      - echo Entering post_build phase...
      - echo Build completed on `date`
