version: 0.2
phases:
  install:
    commands:
      - python --version
      - pip install -r requirements.txt
      - pip install -e .
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - pytest ./tests
      - pylint --errors-only ./services
      - env
  build:
    commands:
      - echo Entering build phase
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo Tagging docker image
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Build completed on `date`
