AWSTemplateFormatVersion: "2010-09-09"
Description:
Resources:
    DummyServer:
        Type: AWS::ECS::Service
        Properties:
            Cluster: sample-flask
            #            DeploymentConfiguration:
            #                DeploymentConfiguration
            #            DeploymentController:
            #                DeploymentController
            DesiredCount: 1
            #            EnableECSManagedTags: Boolean
            HealthCheckGracePeriodSeconds: 30
            LaunchType: EC2
            #            LoadBalancers:
            #                - LoadBalancer
            #            NetworkConfiguration:
            #                NetworkConfiguration
            #            PlacementConstraints:
            #                - PlacementConstraint
            #            PlacementStrategies:
            #                - PlacementStrategy
            #            PlatformVersion: String
            #            PropagateTags: String
            #            Role: String
            SchedulingStrategy: REPLICA
            ServiceName: moviesite
            ServiceRegistries:
                - ServiceRegistry
            Tags:
                - Tag
            TaskDefinition: String
    MyTask:
        Type: AWS::ECS::TaskDefinition
        Properties:
            ContainerDefinitions:
                -
                    Name: "sample-api"
                    Image: "725150092860.dkr.ecr.eu-west-1.amazonaws.com/sample-flask-app:latest"
                    Cpu: "1"
#                    EntryPoint:
#                        - "sh"
#                        - "-c"
                    Memory: "0.2GB"
#                    Command:
#                        - "/bin/sh -c \"while true; do /bin/date > /var/www/my-vol/date; sleep 1; done\""
                    Essential: false
#                    VolumesFrom:
#                        -   SourceContainer:
#                                Ref: "AppName"

            Cpu: String
            ExecutionRoleArn: String
            Family: String
            InferenceAccelerators:
                - InferenceAccelerator
            IpcMode: String
            Memory: String
            NetworkMode: String
            PidMode: String
            PlacementConstraints:
                - TaskDefinitionPlacementConstraint
            ProxyConfiguration:
                ProxyConfiguration
            RequiresCompatibilities:
                - String
            Tags:
                - Tag
            TaskRoleArn: String
            Volumes:
                - Volume
