AWSTemplateFormatVersion: "2010-09-09"
Description: "flask-crud-app"
Parameters:
  GithubSecret:
    # ALL RESOURCES SHOULD HAVE A TAG WITH THIS STRING
    Description: "The github secret."
    Type: String
    Default: "VPC Public and Private with NAT"
Resources:
  ArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
          - '-'
          - - cicd
            - Ref: AWS::AccountId
    DeletionPolicy: Delete

  CodeBuildRole:
    Description: "Allow code build"
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: "CodeBuildPolicy"
          PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogStream
                  - codecommit:*
                  - ecr:*
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                  - s3:*
                Effect: Allow
                Resource: "*"
  CodePipelineServiceRole:
    Description: "Allow code pipeline access to s3"
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: "s3Access"
          PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject*
                  - s3:GetBucket*
                  - s3:List*
                  - s3:DeleteObject*
                  - s3:PutObject*
                  - s3:Abort*
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  - iam:PassRole
                Effect: Allow
                Resource:
                  - Fn::GetAtt:
                      - ArtifactStore
                      - Arn
                  - Fn::Join:
                      - ''
                      - - Fn::GetAtt:
                            - ArtifactStore
                            - Arn
                        - "/*"
                  - Fn::Join:
                      - ''
                      - - Fn::GetAtt:
                            - CodeBuildProject
                            - Arn
            Version: '2012-10-17'
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: MyProject
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildRole
          - Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0
        EnvironmentVariables:
            - Name: IMAGE_TAG
              Value: latest
            - Name: AWS_ACCOUNT_ID
              Value: !Ref AWS::AccountId
            - Name: IMAGE_REPO_NAME
              Value: sample-flask-app
      Source:
        Type: CODEPIPELINE
        BuildSpec: "cicd/buildspec.yml"
        GitCloneDepth: 1
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location:
          Ref: ArtifactStore
        Type: S3
      Name: sample-flask-app-pipeline
      RoleArn:
        Fn::GetAtt:
          - CodePipelineServiceRole
          - Arn
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: donedeal-giorgio
                Repo: sample-flask-app
                Branch: master
                OAuthToken: !Ref GithubSecret
                PollForSourceChanges: false
              Name: MasterCommit
              OutputArtifacts:
                - Name: source
              RunOrder: 1
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName:
                  Ref: CodeBuildProject
              InputArtifacts:
                - Name: source
              Name: SampleCodeBuild
              RunOrder: 1
          Name: Build
  AppPipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GithubSecret
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref CodePipeline
      TargetAction: MasterCommit
      Name: AppPipelineWebhook
      TargetPipelineVersion: !GetAtt CodePipeline.Version
      RegisterWithThirdParty: true
